packages:
  - apps/*

ignoredBuiltDependencies:
  - unrs-resolver

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nestjs-pino
  - sharp
